[CCXDEV-14562] New table for runtimes heartbeats
RedHatInsights/insights-results-aggregator pull request #2080
Opened 2024-11-04 10:58 UTC by ikerreyes

A migration included in the DVO ones (for simplicity) creates a new table to store runtimes heartbeats data (basically ID and timestamp).

Included in the DVO ones to avoid creating new migration schema and another entry point. In addition, this table will be populated by DVO-writer (a modified version of the service) and updated by a new service.

2024-11-04 10:59 UTC, ikerreyes commented on migration/dvomigrations/mig_0005_runtimes_heartbeats_last_check.go
> +			CREATE TABLE runtimes.heartbeats (
Not sure if we are allowed to create tables with this naming, or we need to stick to dvo ones.

2024-11-04 11:11 UTC, juandspy requested changes
please add some unit tests: https://github.com/RedHatInsights/insights-results-aggregator/blob/master/migration/dvomigrations/actual_migrations_test.go

2024-11-04 11:28 UTC, ikerreyes commented
> please add some unit tests: https://github.com/RedHatInsights/insights-results-aggregator/blob/master/migration/dvomigrations/actual_migrations_test.go

Is it worth for a PoC?

2024-11-04 11:48 UTC, ikerreyes commented on migration/dvomigrations/mig_0005_runtimes_heartbeats_last_check.go
> +			CREATE TABLE runtimes.heartbeats (
Seems that is not allowed: `schema \"runtimes\" does not exist"`

2024-11-04 11:58 UTC, juandspy commented
> > please add some unit tests: https://github.com/RedHatInsights/insights-results-aggregator/blob/master/migration/dvomigrations/actual_migrations_test.go
> 
> Is it worth for a PoC?

I think so. I'd leave BDD and IQE tests apart, but for Go repos UTs are a must IMO. It's a really simple way of making it easier for reviewers

2024-11-04 12:04 UTC, ikerreyes commented
> > > please add some unit tests: https://github.com/RedHatInsights/insights-results-aggregator/blob/master/migration/dvomigrations/actual_migrations_test.go
> > 
> > 
> > Is it worth for a PoC?
> 
> I think so. I'd leave BDD and IQE tests apart, but for Go repos UTs are a must IMO. It's a really simple way of making it easier for reviewers

IMO it is wasted effort as we know this code is never going to be reused and will be dropped. But I will stick to your policies.

2024-11-05 10:03 UTC, ikerreyes commented on migration/dvomigrations/mig_0005_runtimes_heartbeats_last_check.go
> +			CREATE TABLE runtimes.heartbeats (
Sticked to dvo ones for simplicity

2024-11-05 10:07 UTC, juandspy approved these changes

2024-11-06 08:06 UTC, merged